[tools]
rust = "latest"

[env]
RUST_BACKTRACE = "1"

[tasks]
default = "cargo run"
run = "cargo run"
build = "cargo build"
test = "cargo test"
check = "cargo check"
clean = "cargo clean"
fmt = "cargo fmt"
clippy = "cargo clippy"
setup = "cargo install cargo-watch"
watch = "cargo watch -c -w src -x run"