# WASMビルドタスク
["build-wasm"]
description = "WASMをビルドする（infoログ）"
run = '''
  wasm-pack build --release --target web --out-dir ./web/pkg
  echo "WASMビルドが完了しました: ./web/pkg/"
'''

["build-wasm-debug"]
description = "WASMをビルドする（debugログ）"
env = { RUST_LOG = "debug" }
run = '''
  wasm-pack build --release --target web --out-dir ./web/pkg
  echo "WASMビルドが完了しました: ./web/pkg/"
'''

["build-wasm-release"]
description = "WASMをビルドする（releaseログなし）"
env = { RUST_LOG = "error" }
run = '''
  wasm-pack build --release --target web --out-dir ./web/pkg
  echo "WASMビルドが完了しました: ./web/pkg/"
'''

[serve]
description = "ローカルサーバーを起動する（web/ をルート）"
run = "miniserve web --port 8080"
